# An example deployment into kubernetes.
apiVersion: v1
kind: Secret
metadata:
  name: nimble-api-credentials
  namespace: prometheus
type: Opaque
stringData:
  username: ARRAY_USERNAME
  password: ARRAY_PASSWORD

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nimble-metrics-exporter
  name: nimble-metrics-exporter
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nimble-metrics-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nimble-metrics-exporter
      name: nimble-metrics-exporter
      namespace: prometheus
    spec:
      containers:
        - name: nimble-metrics-exporter
          image: chrisportman/nimble_metric_exporter:0.1.2
          env:
            - name: NIMBLE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nimble-api-credentials
                  key: username
            - name: NIMBLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nimble-api-credentials
                  key: password
            - name: NIMBLE_SSL_NO_VERIFY
              value: "true"
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 9490
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 9490
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 9490
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nimble-metrics-exporter
  name: nimble-metrics-exporter
  namespace: prometheus
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: http-metrics
      port: 9490
      protocol: TCP
      targetPort: 9490
  selector:
    app.kubernetes.io/name: nimble-metrics-exporter
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: nimble-storage-exporter
  namespace: prometheus
spec:
  jobName: nimble-metrics-exporter
  scrapeInterval: 15s
  scrapeTimeout: 10s
  relabelings:
    - action: replace
      sourceLabels:
        - __address__
      targetLabel: __param_target
    - action: replace
      sourceLabels:
        - __param_target
      targetLabel: instance
    - action: replace
      replacement: nimble-metrics-exporter.prometheus.svc.cluster.local:9490
      targetLabel: __address__
  staticConfigs:
    - labels:
        scrape_interval: 15s
      targets:
        - nimble01.example.com
