name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Set Version and LDFLAGS
        env:
          VERSION_PKG: "github.com/ChrisPortman/nimble_metric_exporter/internal/version"
        run: |
          echo "VERSION=\"$(git describe --tags --abbrev=8 --dirty --always)\"" >> $GITHUB_ENV
          echo "DATE=\"$(date)\"" >> $GITHUB_ENV
          echo "GOVERSION=\"$(go version)\"" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Build
        env:
          VERSION_PKG: "github.com/ChrisPortman/nimble_metric_exporter/internal/version"
        run: |
          go build -v -trimpath \
            -ldflags="-s -w \
              -X '${VERSION_PKG}.Version=${VERSION}' \
              -X '${VERSION_PKG}.BuildDate=${DATE}' \
              -X '${VERSION_PKG}.GoVersion=${GOVERSION}'" \
            -o ./bin/ ./...

      - name: Upload Build Output
        uses: actions/upload-artifact@v4
        with:
          name: nimble_exporter
          path: ./bin/nimble_exporter
