name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Set Version and LDFLAGS
        env:
          VERSION_PKG: "github.com/ChrisPortman/nimble_metric_exporter/internal/version"
        run: |
          export VERSION="$(git describe --tags --abbrev=8 --dirty --always)"
          export DATE="$(date)"
          export GOVERSION="$(go version)"
          export LDFLAGS="-s -w"
          export LDFLAGS="$LDFLAGS -X '${VERSION_PKG}.Version=${VERSION}'"
          export LDFLAGS="$LDFLAGS -X '${VERSION_PKG}.BuildDate=${DATE}'"
          export LDFLAGS="$LDFLAGS -X '${VERSION_PKG}.GoVersion=${GOVERSION}'"
          echo "LDFLAGS=\"$LDFLAGS\"" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Build
        run: go build -v -o ./bin/ -trimpath -ldflags ${LDFLAGS} ./...

      - name: Upload Build Output
        uses: actions/upload-artifact@v4
        with:
          name: nimble_exporter
          path: ./bin/nimble_exporter
